services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ./data/ollama:/root/.ollama


  chatbot:
    build: .
    container_name: chatbot
    ports:
      - 3000:3000
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - CHAINLIT_HOST=0.0.0.0
      - CHAINLIT_PORT=3000
